DROP DATABASE IF EXISTS datasPage;
CREATE DATABASE datasPage;
SET character_set_client = utf8;
SET character_set_connection = utf8;
SET character_set_results = utf8;
SET collation_connection = utf8_general_ci;

USE datasPage;

CREATE TABLE login(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	usuario VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL
);

CREATE TABLE cabecalho(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	logo VARCHAR(60)NOT NULL,
	menu1 VARCHAR(60)NOT NULL,
	menu2 VARCHAR(60)NOT NULL,
	menu3 VARCHAR(60)NOT NULL,
	contato VARCHAR(60)NOT NULL
);

CREATE TABLE banner(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	titulo VARCHAR(60)NOT NULL,
	subtitulo VARCHAR(60)NOT NULL,
	botao1 VARCHAR(60)NOT NULL,
	botao2 VARCHAR(60)NOT NULL,
	imagem_banner VARCHAR(500)
);

CREATE TABLE cards(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	emoticon VARCHAR(500) NOT NULL,
	titulo VARCHAR(50) NOT NULL,
	subtitulo VARCHAR(100) NOT NULL
);

CREATE TABLE servicos(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	titulo VARCHAR(50) NOT NULL,
	subtitulo VARCHAR(100) NOT NULL,
	link VARCHAR(50) NOT NULL,
	video VARCHAR(100) NOT NULL
);

CREATE TABLE catalogos(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	titulo VARCHAR(100) NOT NULL,
	subtitulo VARCHAR(100) NOT NULL,
	imagem VARCHAR(500) NOT NULL
);

CREATE TABLE pq_nos(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	titulo VARCHAR(50) NOT NULL,
	subtitulo VARCHAR(100) NOT NULL,
	imagem VARCHAR(500) NOT NULL
);

CREATE TABLE motivos(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	icone VARCHAR(100) NOT NULL,
	motivo VARCHAR(100) NOT NULL,
	descricao VARCHAR(150) NOT NULL
);

CREATE TABLE elogios(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	imagem VARCHAR(500) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	empresa VARCHAR(100) NOT NULL,
	nota DECIMAL(2,1) NOT NULL,
	elogio TEXT NOT NULL
);

CREATE TABLE footer_esquerdo(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	descricao VARCHAR(500) NOT NULL,
	icone VARCHAR(500) NOT NULL
);

CREATE TABLE footer_direito(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	 coluna1 VARCHAR(50) NOT NULL,
	 coluna2 VARCHAR(50) NOT NULL,
	 coluna3 VARCHAR(50) NOT NULL
);

CREATE TABLE rodape(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	esquerdo VARCHAR(100) NOT NULL,
	centro VARCHAR(50) NOT NULL,
	direito VARCHAR(50) NOT NULL
);
