version: "3"
services:
  mysql:
    image: mysql
    volumes:
      - portfolio-vol:/var/lib/mysql
      - ./db/tabela:/docker-entrypoint-initdb.d
    networks:
      - todolist
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: datasPage
  docker-node:
    image: docker-node
    volumes:
      - ./backend:/home/node/app
    networks:
      - todolist
    ports:
      - '80:8080'
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: datasPage
    depends_on: 
      - mysql

volumes:
  portfolio-vol:
networks:
  todolist: